version: "3"
services:
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-config.yml:/otel-config.yml
      - ./logs:/logs
    command: ["--config=/otel-config.yml"]
    ports:
      - "4317:4317"