receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
      - action: insert
        key: attributes.logstash
        from_attribute: body

exporters:
  debug:
    verbosity: detailed
  file:
    path: /logs/otel-logs.log
    format: json

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [debug, file]

  telemetry:
    logs:
      level: debug
      initial_fields:
        service: "collector"